version: '3'
services:
  web:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile-web
    ports:
      - "8080:80"
    volumes:
    - .:/var/www/html:cached
  db:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile-db
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: XsportsShoppingMalldb
      MYSQL_ROOT_PASSWORD: example
      MYSQL_ROOT_HOST: "%"
      TZ: Asia/Seoul
    volumes:
    - ./db_data:/var/lib/mysql