version: '3'
services:
  web:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "8080:80"
    volumes:
    - .:/var/www/html
  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: Xsportsdb
      MYSQL_ROOT_HOST: "%"
  #     TZ:Asia/Seoul
  # volumes:
  #     - ./db/mysql/data:/var/lib/mysql /
  #     - ./db/mysql/config:/etc/mysql/conf.d
  #     - ./db/mysql/init:/docker-entrypoint-initdb.d